### ISSUE TITLE
使用椰奶插件时报错

### ISSUE THREAD

**Issue by XJLZ** [XasYer/ws-plugin#14]
bot框架:TRSS-Yunzai+NTQQ
用的red分支
在使用[椰奶插件](https://www.yenai.ren/features/Pixiv.html)的Pixiv功能时
报错如下：
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:593:10)
    at Object.readFileSync (node:fs:469:35)
    at getFileInfo (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/tool.js:64:21)
    at upload (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/tool.js:111:28)
    at uploadImg (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/tool.js:29:24)
    at makeNodeMsg (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/message.js:674:39)
    at sendNodeMsg (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/message.js:621:31)
    at makeSendMsg (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/message.js:113:34)
    at QQRedBot.sendGroupMsg (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/bot.js:219:79)
    at Object.sendMsg (file:///home/ubuntu/Yunzai/plugins/ws-plugin/model/red/bot.js:60:34)

**Comment by xiaoye12123** [comment]
什么指令

**Comment by XJLZ** [comment]
> 什么指令

#setu、#看看日榜

**Comment by xiaoye12123** [comment]
> > 什么指令
> 
> #setu、#看看日榜

未复现

**Comment by XJLZ** [comment]
> > > 什么指令
> > 
> > 
> > #setu、#看看日榜
> 
> 未复现

阿哲，😮

**Comment by XJLZ** [comment]
会不会是配置的问题，这是我ws-config.yaml的配置：
![1111](https://github.com/xiaoye12123/ws-plugin/assets/28652248/ae33ec21-057a-465c-b4dc-a2e25689f837)
其他配置是默认，就在servers加了一个服务
