### ISSUE TITLE
初次使用报错

### ISSUE THREAD

**Issue by yhzcake** [XasYer/ws-plugin#21]
[YZ-V4.0.22][13:04:31.103][ERRO] 加载插件错误：ws-plugin
[YZ-V4.0.22][13:04:31.103][ERRO] Error: Cannot find module '/D:/nonebot/yunzaijs/src/runtime.js' imported from D:\nonebot\yunzaijs\lib\plugins\runtime.js
    at finalizeResolution (D:\nonebot\yunzaijs\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:352:11)
    at moduleResolve (D:\nonebot\yunzaijs\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (D:\nonebot\yunzaijs\node_modules\ts-node\dist-raw\node-internal-modules-esm-resolve.js:912:11)
    at D:\nonebot\yunzaijs\node_modules\ts-node\src\esm.ts:218:35
    at entrypointFallback (D:\nonebot\yunzaijs\node_modules\ts-node\src\esm.ts:168:34)
    at D:\nonebot\yunzaijs\node_modules\ts-node\src\esm.ts:217:14
    at addShortCircuitFlag (D:\nonebot\yunzaijs\node_modules\ts-node\src\esm.ts:409:21)
    at resolve (D:\nonebot\yunzaijs\node_modules\ts-node\src\esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:864:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:302:30)

**Comment by yhzcake** [comment]
用的是yunzai-next

**Comment by XasYer** [comment]
不支持
![image](https://github.com/user-attachments/assets/bfd958c5-4646-41f4-bf36-188daac260f4)

**Comment by yhzcake** [comment]
好的

**Comment by XasYer** [comment]
并且这是yunzai-next自己引用不到文件,与本插件无关

**Comment by yhzcake** [comment]
额,我问一下,我想用这个插件反向ws连到onebot上具体怎么配置?我不想用yunzai自带的icqq登录

**Comment by yhzcake** [comment]
![a3285dc618ed46148b97bd60cba26158](https://github.com/user-attachments/assets/81e5b3ee-6628-4cb5-a54c-b1edbf008443)

**Comment by XasYer** [comment]
连接trss的onebot端口

**Comment by yhzcake** [comment]
具体一点?就是这个页面反向ws那里,怎么填?或者通过nonebot获取qq消息的话怎么弄?
